apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: discord-statusbot
  name: discord-statusbot-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
     path: /volumes/discord-statusbot
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-statusbot-pv-claim
  labels:
    app: discord-statusbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discord-statusbot-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discord-statusbot
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: discord-statusbot-pv-claim
      containers:
      - name: discord-statusbot
        image: msniveau/discord-statusbot
        args: ["-vv", "--config", "/mnt/config.ini"]
        volumeMounts:
        - name: storage # must match the volume name, above
          mountPath: "/mnt"

